# View Resolver Setup for JSPs
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# SQLite Database Connection Properties
spring.datasource.url=jdbc:sqlite:global_edu_advisors.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Keeps the embedded web server running properly during local testing
server.servlet.context-path=/
